model:
  name: 'supervised_transformer'
  d_model: 256
  nhead: 8
  d_ff: 2048
  num_layers: 8
training:
  epochs: 20
  patience: 10
  batch_size: 2
  num_workers: 4
  debug: True
evaluation:
  beta: 2
  class_weights: null
  weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
do_train: True
task: "classification"