# model:
name: "decomp_fedformer_encoder"
version: "Wavelets"
mode_select: "random"
modes: 64
base: "legendre"
cross_activation: tanh
d_model: 256
num_heads: 8
num_layers: 8
d_ff: 2048
moving_avg: [50]
factor: 3
dropout: 0.2
output_attention: False
activation: "gelu"
# training:
epochs: 500
batch_size: 8
num_workers: 4
patience: 10
lr: 0.0001
# evaluation:
beta: 2
weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
task: "classification"