# model:
name: "patch_tst"
d_model: 256
d_ff: 512
num_heads: 8
num_layers: 8
dropout: 0.1
head_dropout: 0.1
masking_ratio: 0
masking_ratio_pretraining: 0.5
patch_len: 16
stride: 16
use_patch: True
freeze: False
# training:
optimizer: AdamW
epochs: 500
batch_size: 64
num_workers: 4
lr: 0.0001
weight_decay: 0.0001
patience: 20
scheduler: False
# evaluation:
beta: 2
weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
task: "classification"