model:
  name: "pretraining_patch_tst"
  d_model: 256
  d_ff: 512
  num_heads: 8
  num_layers: 8
  dropout: 0.1
  head_dropout: 0.1
  masking_ratio: 0.4
  patch_len: 16
  stride: 16
  use_patch: True
training:
  optimizer: Adam
  epochs: 400
  batch_size: 128
  num_workers: 4
  lr: 0.0001
  weight_decay: 0
  patience: 20
  scheduler: False
evaluation:
  beta: 2
  class_weights: null
  weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
task: "imputation"