model:
  name: "patch_tst"
  d_model: 256
  d_ff: 512
  num_heads: 8
  num_layers: 8
  dropout: 0.1
  head_dropout: 0.1
  patch_len: 16
  stride: 8
  use_patch: True
  masking_ratio: 0
training:
  optimizer: Adam
  epochs: 100
  batch_size: 32
  num_workers: 2
  lr: 0.0001
  weight_decay: 0
  patience: 20
  scheduler: False
evaluation:
  beta: 2
  class_weights: null
  weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
task: "classification"