model:
  name: "patch_tst"
  d_model: 512
  d_ff: 1024
  num_heads: 16
  num_layers: 16
  dropout: 0.2
  head_dropout: 0.2
  patch_len: 16
  stride: 8
  use_patch: True
training:
  optimizer: Adam
  epochs: 400
  batch_size: 16
  num_workers: 4
  lr: 0.0001
  weight_decay: 0
  patience: 20
  scheduler: False
evaluation:
  beta: 2
  class_weights: null
  weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
task: "classification"