model:
  name: "finetuning_patch_tst"
  d_model: 256
  d_ff: 512
  num_heads: 8
  num_layers: 8
  dropout: 0.1
  head_dropout: 0.1
  patch_len: 16
  stride: 16
  masking_ratio: 0
  use_patch: True
  freeze: True
  l2_reg: 0
  global_reg: False
training:
  optimizer: Adam
  epochs: 400
  batch_size: 64
  num_workers: 4
  lr: 0.001
  weight_decay: 0
  patience: 20
  scheduler: False
evaluation:
  beta: 2
  class_weights: null
  weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
task: "classification"