model:
  name: "pretraining_masked_autoencoder"
  enc_d_model: 256
  enc_d_ff: 512
  enc_num_heads: 8
  enc_num_layers: 8
  dec_d_model: 256
  dec_d_ff: 512
  dec_num_heads: 8
  dec_num_layers: 2
  dropout: 0.1
  patch_len: 16
  stride: 8
  use_patch: True
  masking_ratio: 0.75
training:
  optimizer: AdamW
  epochs: 500
  batch_size: 64
  num_workers: 4
  lr: 0.0001
  weight_decay: 0.0001
  patience: 100
  scheduler: False  # CosineAnnealingWarmRestarts
evaluation:
  beta: 2
  class_weights: null
  weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
task: "pretraining_masked_autoencoder"