model:
  name: "pretraining_masked_autoencoder"
  enc_d_model: 256
  enc_d_ff: 512
  enc_num_heads: 8
  enc_num_layers: 8
  dec_d_model: 256
  dec_d_ff: 512
  dec_num_heads: 8
  dec_num_layers: 8
  dropout: 0.1
  head_dropout: 0.1
  patch_len: 16
  stride: 16
  use_patch: True
  masking_ratio: 0.1
training:
  optimizer: Adam
  epochs: 400
  batch_size: 32
  num_workers: 2
  lr: 0.0001
  weight_decay: 0
  patience: 20
  scheduler: False
evaluation:
  beta: 2
  class_weights: null
  weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
task: "autoencoder_pretraining"