ema_decay: 0.9998
ema_end_decay: 0.99999
instance_norm_target_layer: true
layer_norm_target_layer: false
layer_norm_targets: true
end_of_block_targets: false

depth: 4
num_heads: 8
embed_dim: 64
mlp_ratio: 2
average_top_k_layers: 2
clone_batch: 4

encoder_dropout: 0.1
post_mlp_drop: 0
attention_dropout: 0.1
activation_dropout: 0.1

cls_loss: 0.0

ema_encoder_only: false