# model:
name: "cnn_transformer"
d_model: 256
d_ff: 512
num_heads: 8
num_layers: 8
dropout: 0.1
num_cnn: 5
# training:
epochs: 500
batch_size: 16
num_workers: 4
patience: 20
optimizer: Adam
lr: 0.0001
weight_decay: 0
scheduler: False
# evaluation:
beta: 2
weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
task: "classification"