model:
  name: "cnn_transformer"
  d_model: 1024
  d_ff: 2048
  num_heads: 8
  num_layers: 4
  dropout: 0.2
training:
  epochs: 400
  batch_size: 32
  num_workers: 4
  patience: 10
  lr: 0.0001
evaluation:
  beta: 2
  class_weights: null
  weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
task: "classification"