model:
  name: "cnn_encoder"
  d_model: 256
  num_cnn: 5
training:
  epochs: 400
  batch_size: 32
  num_workers: 4
  patience: 20
  optimizer: Adam
  lr: 0.0001
  weight_decay: 0
  scheduler: False
evaluation:
  beta: 2
  class_weights: null
  weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
task: "classification"