model:
  name: "cnn_encoder"
  d_model: 256
  d_ff: 2048
  num_heads: 8
  num_layers: 8
training:
  epochs: 400
  batch_size: 8
  num_workers: 4
  patience: 10
  lr: 0.0001
evaluation:
  beta: 2
  class_weights: null
  weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
task: "classification"