# model:
name: "transformer"
d_model: 256
d_ff: 512
num_heads: 8
num_layers: 8
dropout: 0.1
pos_encoding: fixed                                                                                                                                                                                                           
activation: relu
normalization_layer: LayerNorm
freeze: False
l2_reg: 0
global_reg: False
# training:
optimizer: Adam
epochs: 500
batch_size: 16
num_workers: 4
lr: 0.00001
weight_decay: 0
patience: 20
scheduler: False
# evaluation:
beta: 2
weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
task: "classification"