model:
  name: "transformer"
  d_model: 2048
  d_ff: 2048
  num_heads: 8
  num_layers: 8
  dropout: 0.1
  pos_encoding: fixed                                                                                                                                                                                                           
  activation: relu
  normalization_layer: LayerNorm
  freeze: False
  l2_reg: 0
  global_reg: False
training:
  optimizer: Adam
  epochs: 400
  batch_size: 8
  num_workers: 4
  lr: 0.00001
  weight_decay: 0
  patience: 20
  scheduler: False
evaluation:
  beta: 2
  class_weights: null
  weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
task: "classification"