model:
  name: "mlp"
  dropout: 0.0
  use_patch: False
training:
  optimizer: AdamW
  epochs: 400
  batch_size: 64
  num_workers: 4
  lr: 0.0001
  weight_decay: 0.0001
  patience: 20
  scheduler: False
evaluation:
  beta: 2
  class_weights: null
  weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
task: "classification"