model:
  name: "supervised_fedformer"
  version: "Fourier"
  mode_select: "random"
  modes: 64  # modes in frequency domain that are kept
  base: "legendre"
  cross_activation: tanh
  seq_len: 2500  # input length encoder of previous ts
  label_len: 2500 # input length decoder (e.g. half of previous ts)
  pred_len: 0 # output length (predicted time steps in decoder)
  enc_in: 12 # input dimensionality encoder
  dec_in: 12 # input dimensionality decoder
  c_out: 12 # output dimensionality 
  d_model: 256
  d_ff: 2048
  num_heads: 8
  e_layers: 8
  d_layers: 1
  moving_avg: [24]
  factor: 3
  dropout: 0.05
  output_attention: False
  activation: "gelu"
training:
  epochs: 400
  batch_size: 16
  num_workers: 4
  patience: 10
  lr: 0.0001
evaluation:
  beta: 2
  class_weights: null
  weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
task: "classification"