model:
  name: "supervised_fedformer"
  version: "Fourier"
  mode_select: "random"
  modes: 64
  base: "legendre"
  cross_activation: tanh
  seq_len: 2500
  label_len: 2500
  pred_len: 0
  enc_in: 12
  dec_in: 12
  c_out: 12
  d_model: 256
  n_heads: 8
  e_layers: 2
  d_layers: 1
  d_ff: 2048
  moving_avg: [24]
  factor: 3
  distil: False
  dropout: 0.05
  output_attention: False
  activation: "gelu"
training:
  epochs: 100
  patience: 10
  batch_size: 1
  num_workers: 4
  lr: 0.0001
  loss: "mse"
  lradj: "type1"
evaluation:
  beta: 2
  class_weights: null
  weights_file: "/usr/stud/roschman/ECGAnalysis/physionet_evaluation/weights.csv"
output_dir: "/usr/stud/roschman/ECGAnalysis/output"
task: "classification"